#!/usr/bin/env python3

import numpy as np

def angleBetween(p1,p2):
    ang1 = np.arctan2(*p1[::-1])
    ang2 = np.arctan2(*p2[::-1])
    return np.rad2deg((ang1-ang2)%(2*np.pi))

w = 100
h = 100

for x in range(w):
    for y in range(h):
        a = (x,y)
        b = (w-x,h-y)
        print(int(round(angleBetween(a,b))))
